# Site settings
title: Nicola Marangoni
email: nicola.marangoni@gmail.com
url: http://marangoni.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ba1c1c #BA1C1C
  secondary: 4D0B0B #4D0B0B
  secondary-dark: 2E0303 #2E0303

# Footer settings
footer:
  copyright: Nicola Marangoni
  location: Around the World
  social: Around the Web
  credits: Contact

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: mail-forward
    url: mailto:nicola.marangoni
  - title: skype
    url: skype:nicola.marangoni
  - title: github
    url: https://github.com/nicolamarangoni
  - title: bitbucket
    url: https://bitbucket.org/nicolamarangoni
  - title: stack-overflow
    url: http://stackoverflow.com/users/2428423/nicolamarangoni
  - title: linkedin
    url: https://www.linkedin.com/pub/nicola-marangoni/0/41a/801
  - title: xing
    url: https://www.xing.com/profile/Nicola_Marangoni
  - title: twitter
    url: https://twitter.com/nicolamarangoni
  - title: facebook
    url: https://www.facebook.com/nic.marango
  - title: google-plus
    url: https://plus.google.com/u/0/108905377619647857736	

# Postal address (add as many lines as necessary)
address:
  - line: Munich
  - line: Germany

# Credits content
credits: 'Email: nicola.marangoni@gmail.com Skype: nicola.marangoni'

# Build settings
markdown: kramdown
permalink: pretty
