# Site settings
title: Nicola Marangoni
email: nicola.marangoni@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my personal blog!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: nicolamarangoni
github_username:  nicolamarangoni
linkedin_profile: nicola-marangoni/0/41a/801
xing_profile: Nicola_Marangoni

# Build settings
markdown: redcarpet
